## Nelson Dong 3

In [1]:
## 1
import numpy as np

data = np.loadtxt('exam_grades.csv', delimiter = ",", skiprows = 1)

print(data)
print(data.shape)

[[2000.       84.5      69.5      86.5      76.2564]
 [2000.       80.       74.       67.       75.3882]
 [2000.       56.       70.       71.5      67.0564]
 ...
 [2003.       97.1429   53.5      67.2222   72.1189]
 [2003.       85.       63.       75.       67.1996]
 [2003.       72.8571   48.5      90.5556   66.4035]]
(233, 5)


In [2]:
## 2
## there are 5 columns in the dataset and 233 observations

In [3]:
## 3
min = data[:, 4].min()
print(min)

max = data[:, 4].max()
print(max)

43.2733
97.5667


In [4]:
## 4
min_year = data[:,0].min()
max_year = data[:,0].max()


print("time period covers from " + str(min_year) + " to " + str(max_year))

time period covers from 2000.0 to 2003.0


In [5]:
## 5
arr = np.empty(0);
count = 0
i = 0
while(i < (data.shape[0] - 1)):
    if(data[i + 1][0] == data[i][0]):
        count += 1
    else :
        arr = np.append(arr, np.array(count))
        count = 0
    i += 1

print(arr)


[85. 74. 35.]


In [6]:
## 6
for line in data:
    print("Year:", line[0], 
          "Min:", line[1:3].min(), 
          "Max:", line[1:3].max(), 
          "Mean:", round(line[1:3].mean(), 3), 
          "Standard Deviation:", round(line[1:3].std(), 3))



Year: 2000.0 Min: 69.5 Max: 84.5 Mean: 77.0 Standard Deviation: 7.5
Year: 2000.0 Min: 74.0 Max: 80.0 Mean: 77.0 Standard Deviation: 3.0
Year: 2000.0 Min: 56.0 Max: 70.0 Mean: 63.0 Standard Deviation: 7.0
Year: 2000.0 Min: 61.0 Max: 64.0 Mean: 62.5 Standard Deviation: 1.5
Year: 2000.0 Min: 72.5 Max: 90.5 Mean: 81.5 Standard Deviation: 9.0
Year: 2000.0 Min: 74.0 Max: 78.5 Mean: 76.25 Standard Deviation: 2.25
Year: 2000.0 Min: 44.0 Max: 60.5 Mean: 52.25 Standard Deviation: 8.25
Year: 2000.0 Min: 82.0 Max: 89.0 Mean: 85.5 Standard Deviation: 3.5
Year: 2000.0 Min: 86.5 Max: 87.5 Mean: 87.0 Standard Deviation: 0.5
Year: 2000.0 Min: 91.0 Max: 98.0 Mean: 94.5 Standard Deviation: 3.5
Year: 2000.0 Min: 79.5 Max: 88.0 Mean: 83.75 Standard Deviation: 4.25
Year: 2000.0 Min: 91.5 Max: 96.0 Mean: 93.75 Standard Deviation: 2.25
Year: 2000.0 Min: 55.0 Max: 79.5 Mean: 67.25 Standard Deviation: 12.25
Year: 2000.0 Min: 80.0 Max: 83.5 Mean: 81.75 Standard Deviation: 1.75
Year: 2000.0 Min: 64.5 Max: 83.5 Me

## Question 2

In [7]:
## differences
list = [[0, 1, 2, 3], [0, 1, 2]]

## the following has an error because np arrays cannot have differing dimensions
# nplist = np.array([[0, 1, 2, 3], [0, 1, 2]])